name: tayseer
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.8.1 <4.0.0"


dependencies:
  flutter:
    sdk: flutter

  audioplayers: ^6.0.0
  cached_network_image: ^3.4.1
  camera: ^0.10.0
  connectivity_plus: ^7.0.0
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  date_picker_timeline: ^1.2.6
  device_info_plus: ^12.3.0
  device_preview: ^1.1.0
  dio: ^5.9.0
  emoji_picker_flutter: ^4.4.0
  equatable: ^2.0.5
  flutter_animate: ^4.5.2
  flutter_bloc: ^9.1.1
  flutter_cache_manager: ^3.4.1
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  flutter_slidable: ^3.0.0
  flutter_svg: ^2.2.2
  gap: ^3.0.1
  get_it: ^9.2.0
  google_sign_in: ^7.2.0
  hexcolor: ^3.0.2
  image_picker: ^1.2.1
  lottie: ^3.3.1
  path_provider: ^2.1.5
  persistent_bottom_nav_bar: ^6.2.1
  pinput: ^6.0.1
  preload_page_view: ^0.2.0
  pretty_dio_logger: ^1.4.0
  shared_preferences: ^2.5.3
  shimmer: ^3.0.0
  sign_in_with_apple: ^6.1.0
  story_view: ^0.16.6
  video_player: ^2.10.1
  video_thumbnail: ^0.5.3
  visibility_detector: ^0.4.0+2
  socket_io_client: ^3.1.3
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  photo_manager: ^3.6.4
  sqflite: ^2.4.1
  path: ^1.9.0
  firebase_core: ^4.3.0
  flutter_local_notifications: ^19.5.0
  firebase_messaging: ^16.1.0
  google_maps_flutter: ^2.14.0
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  uuid: ^4.5.1
  flutter_launcher_icons: ^0.14.4
  google_generative_ai: ^0.4.7
  carousel_slider: ^5.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.6
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animations/
    - assets/icons/
    - assets/lang/
    - assets/sounds/

  fonts:
    - family: ibmp
      fonts:
        - asset: assets/font/IBMPlexSansArabic-Regular.ttf
          weight: 400
        - asset: assets/font/IBMPlexSansArabic-Medium.ttf
          weight: 500
        - asset: assets/font/IBMPlexSansArabic-SemiBold.ttf
          weight: 600
        - asset: assets/font/IBMPlexSansArabic-Bold.ttf
          weight: 700

flutter_icons:
  android: true
  ios: true
  
  image_path: "assets/icons/app_logo_icon.png"